## Exported by node, edge file for each group networks.

## Import RDS file

In [1]:
library(SpiecEasi)
library(phyloseq)
library(NetCoMi)
library(igraph)
library(dplyr)

Attaching package: ‘igraph’


The following object is masked from ‘package:SpiecEasi’:

    make_graph


The following objects are masked from ‘package:stats’:

    decompose, spectrum


The following object is masked from ‘package:base’:

    union



Attaching package: ‘dplyr’


The following objects are masked from ‘package:igraph’:

    as_data_frame, groups, union


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:

## high, networks_pos is clustered only used positive correlation.
high_network <- readRDS("data/3_results/5_network_analysis/5_1_network_inference/high_network_pos.rds")
high_genus_renamed <- readRDS("data/3_results/5_network_analysis/5_1_network_inference/high_phyloseq.rds")
high_genus <- high_genus_renamed$high_genus_renamed ### phyloseq allocation by function
taxtab_high <- high_genus_renamed$taxtab_high
high_net_genus <- high_network$net_genus
high_props_genus <- high_network$props_genus

## low
low_network <- readRDS("data/3_results/5_network_analysis/5_1_network_inference/low_network_pos.rds")
low_genus_renamed <- readRDS("data/3_results/5_network_analysis/5_1_network_inference/low_phyloseq.rds")
low_genus <- low_genus_renamed$low_genus_renamed ### phyloseq allocation by function
taxtab_low <- low_genus_renamed$taxtab_low
low_net_genus <- low_network$net_genus
low_props_genus <- low_network$props_genus

## pibd
pibd_network <- readRDS("data/3_results/5_network_analysis/5_1_network_inference/pibd_network_pos.rds")
pibd_genus_renamed <- readRDS("data/3_results/5_network_analysis/5_1_network_inference/pibd_phyloseq.rds")
pibd_genus <- pibd_genus_renamed$pibd_genus_renamed ### phyloseq allocation by function
taxtab_pibd <- pibd_genus_renamed$taxtab_pibd
pibd_net_genus <- pibd_network$net_genus
pibd_props_genus <- pibd_network$props_genus

## MMI high -> MMI low -> PIBD

In [ ]:
## High version
graph3 <- igraph::graph_from_adjacency_matrix(high_net_genus$adjaMat1, 
                                              weighted = TRUE)
set.seed(42) 
ps_lay_fr <- igraph::layout_with_fr(graph3)


#5. Over edge weighted > 0.4 filtering by csv export method 
edges_raw <- dplyr::filter(high_net_genus$edgelist1)

## First of all, Choose by all nodes
all_nodes <- unique(c(edges_raw$v1, edges_raw$v2))
nodes <- data.frame(Label = all_nodes, stringsAsFactors = FALSE)
nodes$Id <- seq_len(nrow(nodes))  

  
 ## High node representitative nodes number dataframing.
  nodes_repre <- data.frame(Label = all_nodes, stringsAsFactors = FALSE)
  nodes_repre$Id <- seq_len(nrow(nodes)) 

## Second, Label → ID mapping in edges
node_map <- setNames(nodes$Id, nodes$Label)
edges <- edges_raw %>%
  mutate(Source = edges_raw$v1,
         Target = edges_raw$v2,
         Type = "Undirected",
         Weight = adja,
         Sign = ifelse(asso > 0, "Positive", "Negative")) %>%
  select(Source, Target, Type, Weight, Sign, asso)

## Third, Add to information(cluster number)
nodes$cluster <- high_props_genus$clustering$clust1[nodes$Label]
nodes$clr <- high_props_genus$nodeAttr$clr[nodes$Label]
nodes$degree <- high_props_genus$centralities$degree1[nodes$Label] # Degree
nodes$betweenness <- high_props_genus$centralities$between1[nodes$Label] # Betweenness centrality
nodes$closeness <- high_props_genus$centralities$close1[nodes$Label] # Closeness centrality
nodes$eigenvector <- high_props_genus$centralities$eigenv1[nodes$Label] # Eigenvector centrality

## fourth, Add to prevalence, abundance, phylum infomation by each node
woo_phyla <- as.factor(taxtab_high[, "Phylum"])
total_reads <- taxa_sums(high_genus)

woo_df <- data.frame(
  Label = taxa_names(high_genus),
  abundance = as.numeric(total_reads),
  phylum = as.character(woo_phyla),
  stringsAsFactors = FALSE
)

nodes <- merge(nodes, woo_df, by = "Label", all.x = TRUE)

#6. Export to csv file(nodes, edges)
nodes <- nodes[order(nodes$Id), ]
write.csv(nodes, "data/3_results/5_network_analysis/5_2_network_export/high/high_nodes_topology.csv", row.names = FALSE, quote = FALSE)
write.csv(edges, "data/3_results/5_network_analysis/5_2_network_export/high/high_edges.csv", row.names = FALSE, quote = FALSE)

In [ ]:
## low version

graph3 <- igraph::graph_from_adjacency_matrix(low_net_genus$adjaMat1, 
                                              weighted = TRUE)
set.seed(42) 
ps_lay_fr <- igraph::layout_with_fr(graph3)


#5. Over edge weighted > 0.4 filtering by csv export method 
edges_raw <- dplyr::filter(low_net_genus$edgelist1)

## First of all, Choose by all nodes
all_nodes <- unique(c(edges_raw$v1, edges_raw$v2))
nodes <- data.frame(Label = all_nodes, stringsAsFactors = FALSE)
nodes$Id <- seq_len(nrow(nodes)) 


## Second, Label → ID mapping in edges
node_map <- setNames(nodes$Id, nodes$Label)
edges <- edges_raw %>%
  mutate(Source = edges_raw$v1,
         Target = edges_raw$v2,
         Type = "Undirected",
         Weight = adja,
         Sign = ifelse(asso > 0, "Positive", "Negative")) %>%
  select(Source, Target, Type, Weight, Sign, asso)

## Third, Add to information(cluster number)
nodes$cluster <- low_props_genus$clustering$clust1[nodes$Label]
nodes$clr <- low_props_genus$nodeAttr$clr[nodes$Label]
nodes$degree <- low_props_genus$centralities$degree1[nodes$Label] # Degree
nodes$betweenness <- low_props_genus$centralities$between1[nodes$Label] # Betweenness centrality
nodes$closeness <- low_props_genus$centralities$close1[nodes$Label] # Closeness centrality
nodes$eigenvector <- low_props_genus$centralities$eigenv1[nodes$Label] # Eigenvector centrality

## fourth, Add to prevalence, abundance, phylum infomation by each node
woo_phyla <- as.factor(taxtab_low[, "Phylum"])
total_reads <- taxa_sums(low_genus)

woo_df <- data.frame(
  Label = taxa_names(low_genus),
  abundance = as.numeric(total_reads),
  phylum = as.character(woo_phyla),
  stringsAsFactors = FALSE
)

nodes <- merge(nodes, woo_df, by = "Label", all.x = TRUE)


#6. Export to csv file(nodes, edges)
nodes <- nodes[order(nodes$Id), ]
write.csv(nodes, "data/3_results/5_network_analysis/5_2_network_export/low/low_nodes_topology.csv", row.names = FALSE)
write.csv(edges, "data/3_results/5_network_analysis/5_2_network_export/low/low_edges.csv", row.names = FALSE)

In [8]:
nodes

   Label                    Id cluster degree      betweenness closeness
41 Escherichia               1 2       0.031914894 0.005602241 0.5893803
54 Gemmiger_A_73129          2 1       0.074468085 0.206162465 0.7764885
72 Methanobrevibacter_A      3 4       0.005319149 0.000000000 0.3965703
18 Bacteroides_H_857956      4 3       0.021276596 0.000000000 0.5810092
21 Bifidobacterium_388775    5 2       0.037234043 0.049579832 0.6936020
40 Enterococcus_B            6 2       0.005319149 0.000000000 0.4643064
22 Blautia_A_141780          7 2       0.047872340 0.011764706 0.6479538
43 Eubacterium_G_180878      8 1       0.015957447 0.000000000 0.5562608
7  1_Lachnospiraceae(F)      9 2       0.021276596 0.082633053 0.6037520
29 Clostridium_AQ           10 2       0.053191489 0.019887955 0.6675717
53 Gemella                  11 2       0.053191489 0.014565826 0.6827529
56 Granulicatella           12 2       0.047872340 0.023529412 0.6775947
90 Streptococcus            13 2       0.047872340 0.112044818 0.7289228
97 Veillonella_A            14 2       0.042553191 0.010364146 0.6394789
31 Collinsella              15 1       0.015957447 0.000000000 0.4696725
93 Turicibacter             16 8       0.026595745 0.000000000 0.5750843
86 Ruminococcus_E           17 1       0.031914894 0.228011204 0.6603117
45 Faecalibacillus          18 1       0.031914894 0.047058824 0.6853829
92 Thomasclavelia           19 2       0.069148936 0.093277311 0.7608746
32 Coprobacillus            20 2       0.010638298 0.000000000 0.4765851
25 Bulleidia                21 2       0.010638298 0.000000000 0.5067394
13 Alistipes_A_871400       22 3       0.037234043 0.071428571 0.5934521
37 Eggerthella              23 2       0.079787234 0.088235294 0.7508194
12 Akkermansia              24 1       0.005319149 0.000000000 0.4624433
46 Faecalibacterium         25 1       0.047872340 0.259663866 0.7604612
23 Blautia_A_141781         26 2       0.021276596 0.009243697 0.6046759
3  1_CAG-508(F)             27 4       0.015957447 0.023529412 0.3290962
27 CAG-269                  28 5       0.005319149 0.000000000 0.3989540
58 Hominicoprocola          29 4       0.010638298 0.000000000 0.3582944
80 Phocaeicola_A            30 3       0.037234043 0.310084034 0.7149907
⋮  ⋮                        ⋮  ⋮       ⋮           ⋮           ⋮
55 Gordonibacter            69 0       0.000000000 0.000000000 0.0000000
85 Ruminococcus_C_58660     70 1       0.010638298 0.000000000 0.5404775
57 Haemophilus_D_735815     71 2       0.026595745 0.000000000 0.5659539
2  1_Aristaeellaceae(F)     72 4       0.010638298 0.000000000 0.5395051
9  Adlercreutzia_A_404257   73 1       0.021276596 0.000280112 0.5412408
77 Parabacteroides_B_862066 74 3       0.010638298 0.000000000 0.5073607
96 UMGS1071                 75 3       0.015957447 0.000000000 0.5204496
64 Lachnospira              76 1       0.005319149 0.000000000 0.4595547
78 Parasutterella_564865    77 0       0.000000000 0.000000000 0.0000000
74 Nanosynbacter            78 2       0.015957447 0.000000000 0.5651705
14 Alitiscatomonas          79 2       0.005319149 0.000000000 0.4584895
34 Dialister_37762          80 0       0.000000000 0.000000000 0.0000000
63 Lachnoclostridium_B      81 1       0.005319149 0.000000000 0.4987894
73 Nanogingivalis           82 2       0.005319149 0.000000000 0.4895914
48 Faecousia                83 4       0.026595745 0.156862745 0.4641652
75 Odoribacter_865974       84 3       0.005319149 0.000000000 0.4204828
94 UBA5905                  85 3       0.005319149 0.000000000 0.4212645
52 Fusobacterium_C          86 0       0.000000000 0.000000000 0.0000000
49 Fenollaria               87 4       0.005319149 0.000000000 0.2654299
95 UBA644                   88 4       0.010638298 0.000000000 0.3135955
50 Fimenecus                89 0       0.000000000 0.000000000 0.0000000
33 Coprococcus_A_121497     90 6       0.000000000 0.000000000 0.0000000
59 Hominilimicola           91 5       0.010638298 0.002801120 0.5053222
8  1_Mitochondria(F)        92 9       0.000000000 0.000000000 0.0000000
65 Lawsonibacter            93 3       0.005319149 0.000000000 0.4059991
62 Intestinimonas           94 3       0.005319149 0.000000000 0.4071940
38 Eisenbergiella           95 1       0.005319149 0.000000000 0.3890935
42 Eubacterium_F            96 5       0.005319149 0.000000000 0.4093294
16 Anaeromassilibacillus    97 3       0.005319149 0.000000000 0.3368885
69 Massilistercora          98 7       0.000000000 0.000000000 0.0000000
   eigenvector  abundance phylum
41 3.419880e-01 16109     Pseudomonadota
54 7.201189e-02 13408     Bacillota_A_368345
72 3.409790e-04  1113     Methanobacteriota_A_1229
18 1.097175e-02 12285     Bacteroidota
21 4.346413e-01 33102     Actinomycetota
40 4.014577e-02  3531     Bacillota_I
22 6.125070e-01   809     Bacillota_A_368345
43 1.297814e-02   243     Bacillota_A_368345
7  2.411120e-01   534     Bacillota_A_368345
29 6.252033e-01   776     Bacillota_I
53 7.362370e-01  1016     Bacillota_I
56 6.263179e-01   328     Bacillota_I
90 6.146601e-01 10291     Bacillota_I
97 5.884037e-01  2729     Bacillota_C
31 8.103990e-03  4954     Actinomycetota
93 5.112627e-02  1290     Bacillota_I
86 2.180641e-02  7639     Bacillota_A_368345
45 7.250485e-02  4920     Bacillota_I
92 8.982413e-01  4914     Bacillota_I
32 1.027700e-01   649     Bacillota_I
25 1.684392e-01    98     Bacillota_I
13 1.004211e-02  1306     Bacteroidota
37 8.982017e-01  4787     Actinomycetota
12 2.278151e-03 36557     Verrucomicrobiota
46 5.165114e-02 13159     Bacillota_A_368345
23 2.337475e-01 17132     Bacillota_A_368345
3  5.138904e-06  1559     Bacillota_A_368345
27 8.068535e-04  1817     Bacillota_A_368345
58 4.285020e-05   225     Bacillota_A_368345
80 5.240915e-02  8503     Bacteroidota
⋮  ⋮            ⋮         ⋮
55 0.000000e+00  243      Actinomycetota
85 1.690909e-02  211      Bacillota_A_368345
57 4.071147e-01 1372      Pseudomonadota
2  7.839031e-03  141      Bacillota_A_368345
9  1.446833e-02  264      Actinomycetota
77 7.311239e-03  635      Bacteroidota
96 8.117981e-03  497      Bacillota_A_368345
64 3.991681e-03  276      Bacillota_A_368345
78 0.000000e+00  527      Pseudomonadota
74 2.224645e-01  128      Patescibacteria
14 6.492709e-02  127      Bacillota_A_368345
34 0.000000e+00  352      Bacillota_C
63 8.816903e-03  542      Bacillota_A_368345
73 9.318244e-02   27      Patescibacteria
48 3.668864e-04  316      Bacillota_A_368345
75 1.048498e-03   76      Bacteroidota
94 1.057629e-03  107      Bacillota_A_368345
52 0.000000e+00   27      Fusobacteriota
49 5.304470e-07  183      Bacillota_A_368345
95 4.662347e-06   83      Bacillota_A_368345
50 0.000000e+00 3913      Bacillota_A_368345
33 0.000000e+00  105      Bacillota_A_368345
59 5.339904e-03 2653      Bacillota_A_368345
8  0.000000e+00   94      Pseudomonadota
65 7.243437e-04   78      Bacillota_A_368345
62 7.348578e-04   64      Bacillota_A_368345
38 9.543042e-04  661      Bacillota_A_368345
42 1.001637e-03  162      Bacillota_A_368345
16 7.732605e-05  133      Bacillota_A_368345
69 0.000000e+00  456      Bacillota_A_368345

In [ ]:
## pibd


graph3 <- igraph::graph_from_adjacency_matrix(pibd_net_genus$adjaMat1, 
                                              weighted = TRUE)
set.seed(42) 
ps_lay_fr <- igraph::layout_with_fr(graph3)


#5. Over edge weighted > 0.4 filtering by csv export method 
edges_raw <- dplyr::filter(pibd_net_genus$edgelist1)

## First of all, Choose by all nodes
all_nodes <- unique(c(edges_raw$v1, edges_raw$v2))
nodes <- data.frame(Label = all_nodes, stringsAsFactors = FALSE)
nodes$Id <- seq_len(nrow(nodes))  


## Second, Label → ID mapping in edges
node_map <- setNames(nodes$Id, nodes$Label)
edges <- edges_raw %>%
  mutate(Source = edges_raw$v1,
         Target = edges_raw$v2,
         Type = "Undirected",
         Weight = adja,
         Sign = ifelse(asso > 0, "Positive", "Negative")) %>%
  select(Source, Target, Type, Weight, Sign, asso)

## Third, Add to information(cluster number)
nodes$cluster <- pibd_props_genus$clustering$clust1[nodes$Label]
nodes$clr <- pibd_props_genus$nodeAttr$clr[nodes$Label]
nodes$degree <- pibd_props_genus$centralities$degree1[nodes$Label] # Degree
nodes$betweenness <- pibd_props_genus$centralities$between1[nodes$Label] # Betweenness centrality
nodes$closeness <- pibd_props_genus$centralities$close1[nodes$Label] # Closeness centrality
nodes$eigenvector <- pibd_props_genus$centralities$eigenv1[nodes$Label] # Eigenvector centrality

## fourth, Add to prevalence, abundance, phylum infomation by each node
woo_phyla <- as.factor(taxtab_pibd[, "Phylum"])
total_reads <- taxa_sums(pibd_genus)

woo_df <- data.frame(
  Label = taxa_names(pibd_genus),
  abundance = as.numeric(total_reads),
  phylum = as.character(woo_phyla),
  stringsAsFactors = FALSE
)

nodes <- merge(nodes, woo_df, by = "Label", all.x = TRUE)

#6. Export to csv file(nodes, edges)
nodes <- nodes[order(nodes$Id), ]
write.csv(nodes, "data/3_results/5_network_analysis/5_2_network_export/pibd/pibd_nodes_topology.csv", row.names = FALSE)
write.csv(edges, "data/3_results/5_network_analysis/5_2_network_export/pibd/pibd_edges.csv", row.names = FALSE)

In [11]:
nodes

   Label                             Id cluster degree      betweenness
1  1_Bacteria(K)                      1  1      0.010638298 0.000617284
33 Escherichia                        2  1      0.005319149 0.000000000
44 Gemmiger_A_73129                   3  2      0.026595745 0.002160494
14 Bacteroides_H_857956               4  2      0.037234043 0.048765432
52 Hydrotalea                         5 11      0.000000000 0.000000000
16 Bifidobacterium_388775             6  3      0.010638298 0.000308642
31 Enterococcus_B                     7  6      0.015957447 0.054012346
17 Blautia_A_141780                   8  3      0.042553191 0.083333333
34 Eubacterium_G_180878               9  2      0.010638298 0.000000000
57 Lactobacillus                     10  7      0.000000000 0.000000000
5  1_Lachnospiraceae(F)              11  3      0.021276596 0.006790123
21 Clostridium_AQ                    12  5      0.031914894 0.003395062
43 Gemella                           13  1      0.015957447 0.048456790
45 Granulicatella                    14  1      0.042553191 0.083024691
85 Streptococcus                     15  1      0.037234043 0.039814815
90 Veillonella_A                     16  1      0.037234043 0.048765432
84 Staphylococcus                    17  0      0.000000000 0.000000000
58 Lactococcus_A_346120              18  6      0.005319149 0.000000000
23 Collinsella                       19  2      0.037234043 0.064197531
88 Turicibacter                      20  3      0.005319149 0.000000000
80 Ruminococcus_E                    21  4      0.005319149 0.000000000
36 Faecalibacillus                   22  2      0.005319149 0.000000000
87 Thomasclavelia                    23  1      0.031914894 0.045370370
9  Alistipes_A_871400                24  2      0.037234043 0.084567901
47 Holdemanella                      25  2      0.010638298 0.024691358
6  1_Peptostreptococcaceae_256921(F) 26  1      0.010638298 0.000000000
28 Eggerthella                       27  3      0.026595745 0.062037037
37 Faecalibacterium                  28  2      0.063829787 0.226543210
24 Dialister_36337                   29  1      0.010638298 0.023765432
18 Blautia_A_141781                  30  3      0.042553191 0.249691358
⋮  ⋮                                 ⋮  ⋮       ⋮           ⋮
41 Finegoldia                        62  1      0.005319149 0.000000000
38 Faecalimonas                      63  5      0.026595745 0.002777778
42 Fusobacterium_C                   64  1      0.042553191 0.103395062
29 Eisenbergiella                    65  8      0.010638298 0.024691358
46 Haemophilus_D_735815              66  1      0.026595745 0.030864198
73 Peptostreptococcus                67  1      0.010638298 0.000308642
63 Mediterraneibacter_A_155507       68  2      0.021276596 0.000000000
49 Hominilimicola                    69  2      0.021276596 0.000000000
61 Lawsonibacter                     70  2      0.010638298 0.000000000
83 Sphingomonas_L_486704             71 11      0.000000000 0.000000000
82 Sellimonas                        72  3      0.031914894 0.020679012
32 Enterococcus_H_360604             73  6      0.010638298 0.024691358
89 UMGS1071                          74  2      0.026595745 0.231481481
66 Nanosynbacter                     75  1      0.015957447 0.001543210
56 Lacticaseibacillus                76  7      0.000000000 0.000000000
78 Ruminococcus_B                    77  5      0.042553191 0.129629630
51 Hungatella_A_128155               78  5      0.026595745 0.024382716
59 Lancefieldella                    79  1      0.021276596 0.047839506
25 Dialister_37762                   80  2      0.021276596 0.000000000
75 Prevotella                        81  2      0.005319149 0.000000000
10 Alistipes_A_871404                82  9      0.000000000 0.000000000
79 Ruminococcus_C_58660              83  4      0.005319149 0.000000000
39 Faecousia                         84  4      0.015957447 0.020987654
54 Lachnoclostridium_B               85  3      0.010638298 0.151851852
40 Fimenecus                         86  4      0.005319149 0.000000000
35 Evtepia                           87  4      0.005319149 0.000000000
86 Terrisporobacter                  88  3      0.005319149 0.000000000
50 Hominimerdicola                   89 10      0.005319149 0.000000000
68 Onthenecus                        90  0      0.000000000 0.000000000
71 Parasutterella_564865             91  8      0.005319149 0.000000000
   closeness eigenvector  abundance phylum
1  0.3657093 0.0003146949   210     __
33 0.3457030 0.0002794848 30130     Pseudomonadota
44 0.5524187 0.4106847737 10823     Bacillota_A_368345
14 0.5989270 0.5805189058 27198     Bacteroidota
52 0.0000000 0.0000000000   126     Bacteroidota
16 0.4894817 0.0121147770 21583     Actinomycetota
31 0.5249255 0.0049287654  4619     Bacillota_I
17 0.6433284 0.0491272417  1450     Bacillota_A_368345
34 0.4996823 0.1817755002   625     Bacillota_A_368345
57 0.0000000 0.0000000000  5406     Bacillota_I
5  0.5514900 0.0140338028   882     Bacillota_A_368345
21 0.5820470 0.0240018462   581     Bacillota_I
43 0.4556393 0.0020238339  1121     Bacillota_I
45 0.6158444 0.0138314063   801     Bacillota_I
85 0.5837309 0.0098552091  9467     Bacillota_I
90 0.6126517 0.0177513548  6580     Bacillota_C
84 0.0000000 0.0000000000   145     Bacillota_I
58 0.3261954 0.0001114803   397     Bacillota_I
23 0.6223119 0.4436568234  5825     Actinomycetota
88 0.4548885 0.0073562697   980     Bacillota_I
80 0.3768718 0.0072854522  4269     Bacillota_A_368345
36 0.4669742 0.1384879228  2199     Bacillota_I
87 0.6276369 0.0249780433  1181     Bacillota_I
9  0.5866395 0.4808623319  2868     Bacteroidota
47 0.4518045 0.0639059951  2816     Bacillota_I
6  0.4934494 0.0052299311   106     Bacillota_A_368345
28 0.6194287 0.0412237140  2553     Actinomycetota
37 0.7127533 1.0000000000 32826     Bacillota_A_368345
24 0.4181629 0.0012548832   540     Bacillota_C
18 0.6949867 0.1029904116 10189     Bacillota_A_368345
⋮  ⋮         ⋮            ⋮         ⋮
41 0.4030147 0.0012719946   54      Bacillota_A_368345
38 0.5563688 0.0174860451 1615      Bacillota_A_368345
42 0.5699961 0.0086467847 3519      Fusobacteriota
29 0.4979805 0.1297315477  844      Bacillota_A_368345
46 0.5687388 0.0097199087 6846      Pseudomonadota
73 0.3472013 0.0002172658  411      Bacillota_A_368345
63 0.5450196 0.3502117712 2821      Bacillota_A_368345
49 0.5360627 0.4310793146  908      Bacillota_A_368345
61 0.4312788 0.1298344966  229      Bacillota_A_368345
83 0.0000000 0.0000000000   99      Pseudomonadota
82 0.5922114 0.0338737282  749      Bacillota_A_368345
32 0.4138650 0.0008064930  781      Bacillota_I
89 0.6548139 0.3738841649  664      Bacillota_A_368345
66 0.5234617 0.0090302941  115      Patescibacteria
56 0.0000000 0.0000000000   86      Bacillota_I
78 0.6516953 0.0382668836 3809      Bacillota_A_368345
51 0.5295668 0.0105636886  397      Bacillota_A_368345
59 0.5563635 0.0098050687  287      Actinomycetota
25 0.5290434 0.3989432627 2042      Bacillota_C
75 0.3517922 0.0088887718 1588      Bacteroidota
10 0.0000000 0.0000000000   64      Bacteroidota
79 0.3508181 0.0103658187  222      Bacillota_A_368345
39 0.4380572 0.0194388601  107      Bacillota_A_368345
54 0.5837563 0.1401566698  551      Bacillota_A_368345
40 0.3743416 0.0070424785  245      Bacillota_A_368345
35 0.3743483 0.0070431293  125      Bacillota_A_368345
86 0.4466763 0.0033813627  308      Bacillota_A_368345
50 0.3691202 0.0205961832  284      Bacillota_A_368345
68 0.0000000 0.0000000000  369      Bacillota_A_368345
71 0.3778176 0.0179788554 3038      Pseudomonadota